baseURL = "https://www.mildlyjournaling.com/"
languageCode = 'en-us'
title = 'Mildly Journaling'
theme = 'paper'
capitalizeListTitles = false

[params]
  rss = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "apps"
    name = "Apps"
    url = "/apps/"
    weight = 15
  [[menu.main]]
    identifier = "activity"
    name = "Activity"
    url = "/activity/"
    weight = 20

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  taxonomy = ['html']
  term = ['html']
